### PR TITLE
Shape Editor update

### PR DESCRIPTION
**Pull request by gkirgizov**
First part of shape editor refactoring is finished: ShapeEdit was divded to interface and implementation; save-load logic (including working with model repository) was incapsulated is SaveLoadLogic class.

### CODE REVIEW

**Comment by danilaml** [comment]
File mode permissions changed `100644 → 100755`

**Comment by danilaml** [comment]
It looks like there is line endings issue too.

**Comment by gkirgizov** [comment]
What endings should be? CRLF or LF?

**Comment by danilaml** [comment]
@gkirgizov git usually handles it by itself: https://help.github.com/articles/dealing-with-line-endings/#platform-all

**Pull request closed without merging**
